name: Danger

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]

jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macOS-latest
    steps:
    #   - uses: actions/checkout@v4
    #   - uses: ruby/setup-ruby@v1
    #     with:
    #       ruby-version: '2.6'
    #   - uses: actions/cache@v4
    #     with:
    #       path: vendor/bundle
    #       key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
    #       restore-keys: |
    #         ${{ runner.os }}-gems-
    #   - uses: MeilCli/danger-action@v6
    #     with:
    #       plugins_file: 'Gemfile'
    #       install_path: 'vendor/bundle'
    #       danger_file: 'Dangerfile'
    #       danger_id: 'danger-pr'
    #     env:
    #       DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: git checkout
        uses: actions/checkout@v4

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger --verbose
